spring.datasource.url=jdbc:postgresql://localhost:5432/sport
spring.datasource.username=postgres
spring.datasource.password=teamwork.tf
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.default_schema=sport
spring.data.redis.host=localhost
spring.data.redis.port=6380

logging.level.root=DEBUG



sms.api.url=https://sms.ru/sms/send

spring.freemarker.suffix=.ftl
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.settings.auto_import=spring.ftl as spring

server.error.path=/error

